"""Train a Poisson XGBoost model and explain it with SHAP.

The model estimates the Poisson rate parameter ``lambda`` for goals scored by a
team, using the regression features prepared by ``feature_pipeline``.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import polars as pl
import shap
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_poisson_deviance, r2_score
from sklearn.model_selection import train_test_split

try:
    from . import settings
    from .feature_pipeline import build_feature_frame
except ImportError:  # pragma: no cover - supports direct script execution.
    import settings
    from feature_pipeline import build_feature_frame

LOGGER = logging.getLogger(__name__)

MODELS_DIR = settings.MODELS_DIR
FIGURES_DIR = settings.FIGURES_DIR
MODEL_PATH = settings.MODEL_PATH
BEESWARM_PATH = settings.BEESWARM_PATH

FEATURE_COLUMNS: tuple[str, ...] = (
    "world_cup_probability_elo_diff",
    "world_football_elo_ratings_diff",
    "fifa_world_ranking_points_diff",
    "fifa_world_ranking_rank_diff",
    "market_value_diff",
    "avg_overall_diff",
    "avg_pace_diff",
    "avg_stamina_diff",
    "squad_depth_proxy",
    "recent_form_diff",
)
TARGET_COLUMN = "target"


@dataclass(frozen=True, slots=True)
class ModelArtifacts:
    """Paths generated by the training routine."""

    model_path: Path
    beeswarm_path: Path


def load_training_frame(db_path: Path | None = None) -> pl.DataFrame:
    """Load and validate the training dataset."""
    frame = build_feature_frame() if db_path is None else build_feature_frame(db_path)

    frame = frame.drop_nulls()
    missing_columns = [
        column for column in (*FEATURE_COLUMNS, TARGET_COLUMN) if column not in frame.columns
    ]
    if missing_columns:
        raise RuntimeError(f"Training frame is missing columns: {', '.join(missing_columns)}")

    if frame.height == 0:
        raise RuntimeError("Training frame is empty after null filtering.")

    return frame


def prepare_matrices(
    frame: pl.DataFrame,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, list[str]]:
    """Split the Polars frame into train and validation numpy matrices."""
    feature_frame = frame.select(list(FEATURE_COLUMNS))
    target = frame.get_column(TARGET_COLUMN).cast(pl.Float64)

    X = feature_frame.to_numpy()
    y = target.to_numpy()
    feature_names = list(FEATURE_COLUMNS)

    X_train, X_valid, y_train, y_valid = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
    )

    return X_train, X_valid, y_train, y_valid, feature_names


def train_poisson_model(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_valid: np.ndarray,
    y_valid: np.ndarray,
) -> xgb.XGBRegressor:
    """Train an XGBoost regressor with a Poisson objective."""
    model = xgb.XGBRegressor(
        objective="count:poisson",
        n_estimators=500,
        learning_rate=0.03,
        max_depth=4,
        min_child_weight=1.0,
        subsample=0.9,
        colsample_bytree=0.9,
        reg_alpha=0.0,
        reg_lambda=1.0,
        tree_method="hist",
        eval_metric="poisson-nloglik",
        random_state=42,
    )

    model.fit(
        X_train,
        y_train,
        eval_set=[(X_valid, y_valid)],
        verbose=False,
    )

    return model


def explain_model(
    model: xgb.XGBRegressor,
    X_reference: np.ndarray,
    feature_names: list[str],
    output_path: Path = BEESWARM_PATH,
) -> Path:
    """Generate a SHAP beeswarm plot and save it to disk."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_reference)
    explanation = shap.Explanation(
        values=shap_values,
        base_values=explainer.expected_value,
        data=X_reference,
        feature_names=feature_names,
    )

    # Leitura estrita do Beeswarm:
    # cada ponto representa uma observação; a posição no eixo X mostra o impacto
    # direto na predição do modelo. Pontos à direita empurram a previsão para
    # cima; pontos à esquerda a reduzem. A cor codifica apenas o valor alto/baixo
    # da feature naquela linha. Não interpretar essa figura como p-valor, teste
    # de hipótese ou regressão linear clássica.
    plt.figure(figsize=(10, 6))
    shap.plots.beeswarm(explanation, max_display=len(feature_names), show=False)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close()

    return output_path


def save_model(model: xgb.XGBRegressor, output_path: Path = MODEL_PATH) -> Path:
    """Persist the trained XGBoost model to disk."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    model.save_model(str(output_path))
    return output_path


def evaluate_model(
    model: xgb.XGBRegressor,
    X_valid: np.ndarray,
    y_valid: np.ndarray,
) -> dict[str, float]:
    """Compute validation metrics for the Poisson regressor."""
    y_pred = model.predict(X_valid)
    return {
        "mae": mean_absolute_error(y_valid, y_pred),
        "poisson_deviance": mean_poisson_deviance(y_valid, y_pred),
        "r2": r2_score(y_valid, y_pred),
    }


def train_pipeline(db_path: Path | None = None) -> ModelArtifacts:
    """Run the end-to-end training and interpretation pipeline."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
    )

    frame = load_training_frame(db_path)
    LOGGER.info("Loaded training frame with shape %s", frame.shape)

    X_train, X_valid, y_train, y_valid, feature_names = prepare_matrices(frame)
    model = train_poisson_model(X_train, y_train, X_valid, y_valid)

    metrics = evaluate_model(model, X_valid, y_valid)
    LOGGER.info(
        "Validation metrics - MAE: %.4f | Poisson deviance: %.4f | R2: %.4f",
        metrics["mae"],
        metrics["poisson_deviance"],
        metrics["r2"],
    )

    model_path = save_model(model)
    beeswarm_path = explain_model(model, X_valid, feature_names)
    LOGGER.info("Model saved to %s", model_path)
    LOGGER.info("Beeswarm saved to %s", beeswarm_path)

    return ModelArtifacts(model_path=model_path, beeswarm_path=beeswarm_path)


def main() -> int:
    """CLI entrypoint."""
    train_pipeline()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
