"""Train a direct win/draw/loss model for match outcomes.

The existing Poisson model estimates goals. This module adds a categorical
model that optimizes the event the user usually asks for: home win, draw, or
away win. It keeps the same temporal validation discipline used by the Poisson
pipeline and compares validation accuracy with a uniform random baseline.
"""

from __future__ import annotations

import argparse
import logging
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import polars as pl
import xgboost as xgb
from sklearn.metrics import accuracy_score, balanced_accuracy_score, log_loss

try:
    from .feature_pipeline import build_feature_frame
    from .model import (
        CURRENT_WORLD_CUP_COLUMN,
        DEFAULT_VALIDATION_FRACTION,
        FEATURE_COLUMNS,
        MATCH_DATE_COLUMN,
        save_json_artifact,
    )
    from .settings import MODELS_DIR
except ImportError:  # pragma: no cover - supports direct script execution.
    from feature_pipeline import build_feature_frame
    from model import (
        CURRENT_WORLD_CUP_COLUMN,
        DEFAULT_VALIDATION_FRACTION,
        FEATURE_COLUMNS,
        MATCH_DATE_COLUMN,
        save_json_artifact,
    )
    from settings import MODELS_DIR

LOGGER = logging.getLogger(__name__)

OUTCOME_MODEL_PATH = MODELS_DIR / "xgb_outcome_model.json"
OUTCOME_METRICS_PATH = MODELS_DIR / "xgb_outcome_metrics.json"

HOME_WIN_CLASS = 0
DRAW_CLASS = 1
AWAY_WIN_CLASS = 2
OUTCOME_CLASS_LABELS: tuple[str, ...] = ("home_win", "draw", "away_win")
OUTCOME_CLASS_COUNT = len(OUTCOME_CLASS_LABELS)
HOME_GOALS_COLUMN = "home_goals"
AWAY_GOALS_COLUMN = "away_goals"

DEFAULT_XGB_OUTCOME_PARAMS: dict[str, Any] = {
    "objective": "multi:softprob",
    "num_class": OUTCOME_CLASS_COUNT,
    "n_estimators": 400,
    "learning_rate": 0.035,
    "max_depth": 3,
    "min_child_weight": 2.0,
    "subsample": 0.9,
    "colsample_bytree": 0.9,
    "reg_alpha": 0.0,
    "reg_lambda": 1.5,
    "tree_method": "hist",
    "eval_metric": "mlogloss",
    "random_state": 42,
}


@dataclass(frozen=True, slots=True)
class OutcomeModelArtifacts:
    """Paths generated by the outcome training routine."""

    model_path: Path
    metrics_path: Path


def load_outcome_training_frame(db_path: Path | None = None) -> pl.DataFrame:
    """Load historical rows with labels for home win, draw, or away win."""
    frame = (
        build_feature_frame(include_metadata=True)
        if db_path is None
        else build_feature_frame(db_path, include_metadata=True)
    )

    required_columns = (
        *FEATURE_COLUMNS,
        MATCH_DATE_COLUMN,
        HOME_GOALS_COLUMN,
        AWAY_GOALS_COLUMN,
    )
    missing_columns = [column for column in required_columns if column not in frame.columns]
    if missing_columns:
        missing_column_names = ", ".join(missing_columns)
        raise RuntimeError(f"Outcome training frame is missing columns: {missing_column_names}")

    frame = frame.drop_nulls(list(required_columns))
    if frame.height == 0:
        raise RuntimeError("Outcome training frame is empty after null filtering.")

    return _historical_outcome_frame(frame)


def prepare_outcome_matrices(
    frame: pl.DataFrame,
    *,
    validation_fraction: float = DEFAULT_VALIDATION_FRACTION,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, list[str]]:
    """Split the frame temporally into train and validation matrices."""
    if not 0.0 < validation_fraction < 1.0:
        raise ValueError("validation_fraction must be greater than 0 and less than 1.")

    frame = _historical_outcome_frame(frame)
    if frame.height < 2:
        raise RuntimeError("At least two historical rows are required for temporal validation.")

    split_index = int(frame.height * (1.0 - validation_fraction))
    split_index = min(max(split_index, 1), frame.height - 1)

    train_frame = frame.slice(0, split_index)
    valid_frame = frame.slice(split_index)

    X_train, y_train, feature_names = prepare_full_outcome_matrix(train_frame)
    X_valid, y_valid, _ = prepare_full_outcome_matrix(valid_frame)

    return X_train, X_valid, y_train, y_valid, feature_names


def prepare_full_outcome_matrix(frame: pl.DataFrame) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """Build feature and categorical target arrays from a match-level frame."""
    missing_columns = [
        column
        for column in (*FEATURE_COLUMNS, HOME_GOALS_COLUMN, AWAY_GOALS_COLUMN)
        if column not in frame.columns
    ]
    if missing_columns:
        raise RuntimeError(f"Frame is missing columns: {', '.join(missing_columns)}")

    feature_frame = frame.select(list(FEATURE_COLUMNS))
    labels = _outcome_labels(frame)
    return feature_frame.to_numpy(), labels, list(FEATURE_COLUMNS)


def train_outcome_model(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_valid: np.ndarray | None = None,
    y_valid: np.ndarray | None = None,
    *,
    params: dict[str, Any] | None = None,
) -> xgb.XGBClassifier:
    """Train a multiclass XGBoost model for home win/draw/away win."""
    missing_classes = set(range(OUTCOME_CLASS_COUNT)) - set(int(label) for label in y_train)
    if missing_classes:
        labels = ", ".join(OUTCOME_CLASS_LABELS[label] for label in sorted(missing_classes))
        raise RuntimeError(f"Training data does not contain all outcome classes: {labels}")

    model_params = DEFAULT_XGB_OUTCOME_PARAMS | (params or {})
    model = xgb.XGBClassifier(**model_params)

    fit_kwargs: dict[str, Any] = {"verbose": False}
    if X_valid is not None and y_valid is not None:
        fit_kwargs["eval_set"] = [(X_valid, y_valid)]
    model.fit(X_train, y_train, **fit_kwargs)
    return model


def evaluate_outcome_model(
    model: xgb.XGBClassifier,
    X_valid: np.ndarray,
    y_valid: np.ndarray,
    *,
    random_hit_probability: float = 1.0 / OUTCOME_CLASS_COUNT,
) -> dict[str, float]:
    """Evaluate outcome predictions against a uniform random baseline."""
    if y_valid.size == 0:
        raise RuntimeError("Validation target is empty.")

    predicted_labels = model.predict(X_valid).astype(int)
    probabilities = _clip_probabilities(model.predict_proba(X_valid))

    hits = int(np.sum(predicted_labels == y_valid))
    trials = int(y_valid.size)
    accuracy = float(accuracy_score(y_valid, predicted_labels))
    random_accuracy = float(random_hit_probability)

    return {
        "rows": float(trials),
        "hits": float(hits),
        "accuracy": accuracy,
        "balanced_accuracy": float(balanced_accuracy_score(y_valid, predicted_labels)),
        "multiclass_log_loss": float(
            log_loss(y_valid, probabilities, labels=list(range(OUTCOME_CLASS_COUNT)))
        ),
        "multiclass_brier_score": _multiclass_brier_score(y_valid, probabilities),
        "uniform_random_accuracy": random_accuracy,
        "accuracy_lift_vs_uniform_random": accuracy - random_accuracy,
        "uniform_random_log_loss": float(math.log(OUTCOME_CLASS_COUNT)),
        "uniform_random_brier_score": float((OUTCOME_CLASS_COUNT - 1) / OUTCOME_CLASS_COUNT),
        "binomial_p_value_vs_uniform_random": _binomial_one_sided_p_value(
            successes=hits,
            trials=trials,
            p=random_hit_probability,
        ),
    }


def save_outcome_model(model: xgb.XGBClassifier, output_path: Path = OUTCOME_MODEL_PATH) -> Path:
    """Persist the trained outcome model to disk."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    model.save_model(str(output_path))
    return output_path


def outcome_class_distribution(labels: np.ndarray) -> dict[str, int]:
    """Return count by semantic class label."""
    counts = np.bincount(labels.astype(int), minlength=OUTCOME_CLASS_COUNT)
    return {
        OUTCOME_CLASS_LABELS[index]: int(count)
        for index, count in enumerate(counts[:OUTCOME_CLASS_COUNT])
    }


def train_outcome_pipeline(
    db_path: Path | None = None,
    *,
    validation_fraction: float = DEFAULT_VALIDATION_FRACTION,
) -> OutcomeModelArtifacts:
    """Run training, temporal validation, and artifact persistence."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
    )

    frame = load_outcome_training_frame(db_path)
    LOGGER.info("Loaded outcome training frame with shape %s", frame.shape)

    X_train, X_valid, y_train, y_valid, _ = prepare_outcome_matrices(
        frame,
        validation_fraction=validation_fraction,
    )
    validation_model = train_outcome_model(X_train, y_train, X_valid, y_valid)
    metrics = evaluate_outcome_model(validation_model, X_valid, y_valid)
    metrics_payload = {
        **metrics,
        "train_class_distribution": outcome_class_distribution(y_train),
        "validation_class_distribution": outcome_class_distribution(y_valid),
    }
    metrics_path = save_json_artifact(metrics_payload, OUTCOME_METRICS_PATH)

    X_full, y_full, _ = prepare_full_outcome_matrix(frame)
    final_model = train_outcome_model(X_full, y_full)
    model_path = save_outcome_model(final_model)

    LOGGER.info(
        "Outcome validation - accuracy: %.4f | random: %.4f | p-value: %.6g",
        metrics["accuracy"],
        metrics["uniform_random_accuracy"],
        metrics["binomial_p_value_vs_uniform_random"],
    )
    LOGGER.info("Outcome model saved to %s", model_path)
    LOGGER.info("Outcome metrics saved to %s", metrics_path)

    return OutcomeModelArtifacts(model_path=model_path, metrics_path=metrics_path)


def _historical_outcome_frame(frame: pl.DataFrame) -> pl.DataFrame:
    if CURRENT_WORLD_CUP_COLUMN in frame.columns:
        frame = frame.filter(~pl.col(CURRENT_WORLD_CUP_COLUMN))

    if frame.height == 0:
        raise RuntimeError("Outcome frame has no historical rows outside the 2026 World Cup.")

    sort_columns = [MATCH_DATE_COLUMN]
    if "match_id" in frame.columns:
        sort_columns.append("match_id")
    return frame.sort(sort_columns)


def _outcome_labels(frame: pl.DataFrame) -> np.ndarray:
    home_goals = frame.get_column(HOME_GOALS_COLUMN).cast(pl.Float64).to_numpy()
    away_goals = frame.get_column(AWAY_GOALS_COLUMN).cast(pl.Float64).to_numpy()
    return np.where(
        home_goals > away_goals,
        HOME_WIN_CLASS,
        np.where(home_goals == away_goals, DRAW_CLASS, AWAY_WIN_CLASS),
    ).astype(np.int64)


def _clip_probabilities(probabilities: np.ndarray) -> np.ndarray:
    probabilities = np.asarray(probabilities, dtype=float)
    if probabilities.ndim != 2 or probabilities.shape[1] != OUTCOME_CLASS_COUNT:
        raise RuntimeError(
            "Outcome model must return one probability column for each result class."
        )
    probabilities = np.clip(probabilities, 1e-12, 1.0)
    return probabilities / probabilities.sum(axis=1, keepdims=True)


def _multiclass_brier_score(labels: np.ndarray, probabilities: np.ndarray) -> float:
    one_hot = np.eye(OUTCOME_CLASS_COUNT)[labels.astype(int)]
    return float(np.mean(np.sum(np.square(probabilities - one_hot), axis=1)))


def _binomial_one_sided_p_value(*, successes: int, trials: int, p: float) -> float:
    """Return P[X >= successes] for X ~ Binomial(trials, p)."""
    if trials <= 0:
        raise ValueError("trials must be greater than zero.")
    if not 0.0 < p < 1.0:
        raise ValueError("p must be between 0 and 1.")
    if successes <= 0:
        return 1.0
    if successes > trials:
        raise ValueError("successes cannot exceed trials.")

    log_p = math.log(p)
    log_q = math.log1p(-p)
    max_log = -math.inf
    log_terms: list[float] = []
    for k in range(successes, trials + 1):
        log_term = (
            math.lgamma(trials + 1)
            - math.lgamma(k + 1)
            - math.lgamma(trials - k + 1)
            + k * log_p
            + (trials - k) * log_q
        )
        log_terms.append(log_term)
        max_log = max(max_log, log_term)

    tail_probability = math.exp(max_log) * sum(math.exp(term - max_log) for term in log_terms)
    return float(min(1.0, tail_probability))


def build_parser() -> argparse.ArgumentParser:
    """Build CLI parser for the outcome model."""
    parser = argparse.ArgumentParser(description="Train a win/draw/loss outcome model.")
    parser.add_argument("--db-path", type=Path, default=None, help="DuckDB warehouse path.")
    parser.add_argument(
        "--validation-fraction",
        type=float,
        default=DEFAULT_VALIDATION_FRACTION,
        help="Most recent historical fraction used for temporal validation.",
    )
    return parser


def main() -> int:
    """CLI entrypoint."""
    args = build_parser().parse_args()
    train_outcome_pipeline(args.db_path, validation_fraction=args.validation_fraction)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
